# Generated by Django 3.0.7 on 2020-07-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=90)),
                ('address', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=90)),
            ],
        ),
    ]
